<?php

use OAuth2\OAuth2;
use Symfony\Component\HttpFoundation\Request;

class sspmod_oauth2_OAuth2 extends OAuth2
{
    public function getAuthorizeParams( Request $request = null )
    {
        return parent::getAuthorizeParams( $request );
    }

    protected function setDefaultOptions()
    {
        parent::setDefaultOptions(); // TODO: Change the autogenerated stub

        $oauth2config = SimpleSAML_Configuration::getConfig('module_oauth2.php');

        $this->conf[self::CONFIG_SUPPORTED_SCOPES] = array('user_details');
        $this->conf[self::CONFIG_AUTH_LIFETIME] = $oauth2config->getInteger("accessTokenDuration");
        $this->conf[self::CONFIG_ACCESS_LIFETIME] = $oauth2config->getInteger("requestTokenDuration");
        $this->conf[self::CONFIG_REFRESH_LIFETIME] = $oauth2config->getInteger("authTokenDuration");
    }


}